/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding.preview'
import { Route as OnboardingLoadingRouteImport } from './routes/onboarding.loading'
import { Route as OnboardingStepStepRouteImport } from './routes/onboarding.step.$step'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLoadingRoute = OnboardingLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStepStepRoute = OnboardingStepStepRouteImport.update({
  id: '/step/$step',
  path: '/step/$step',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/step/$step': typeof OnboardingStepStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/step/$step': typeof OnboardingStepStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/step/$step': typeof OnboardingStepStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/onboarding/loading'
    | '/onboarding/preview'
    | '/onboarding/step/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/onboarding/loading'
    | '/onboarding/preview'
    | '/onboarding/step/$step'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/onboarding/loading'
    | '/onboarding/preview'
    | '/onboarding/step/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/preview': {
      id: '/onboarding/preview'
      path: '/preview'
      fullPath: '/onboarding/preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/loading': {
      id: '/onboarding/loading'
      path: '/loading'
      fullPath: '/onboarding/loading'
      preLoaderRoute: typeof OnboardingLoadingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step/$step': {
      id: '/onboarding/step/$step'
      path: '/step/$step'
      fullPath: '/onboarding/step/$step'
      preLoaderRoute: typeof OnboardingStepStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingLoadingRoute: typeof OnboardingLoadingRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  OnboardingStepStepRoute: typeof OnboardingStepStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLoadingRoute: OnboardingLoadingRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  OnboardingStepStepRoute: OnboardingStepStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
