/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences.index'
import { Route as PreferencesReferralsRouteImport } from './routes/preferences.referrals'
import { Route as PreferencesLocationRouteImport } from './routes/preferences.location'
import { Route as PreferencesBudgetRouteImport } from './routes/preferences.budget'
import { Route as PreferencesApartmentRouteImport } from './routes/preferences.apartment'
import { Route as PreferencesAlertsRouteImport } from './routes/preferences.alerts'
import { Route as PreferencesAccountRouteImport } from './routes/preferences.account'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding.success'
import { Route as OnboardingPricingRouteImport } from './routes/onboarding.pricing'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding.preview'
import { Route as OnboardingLoadingRouteImport } from './routes/onboarding.loading'
import { Route as OnboardingStepStepRouteImport } from './routes/onboarding.step.$step'

const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesReferralsRoute = PreferencesReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesLocationRoute = PreferencesLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesBudgetRoute = PreferencesBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesApartmentRoute = PreferencesApartmentRouteImport.update({
  id: '/apartment',
  path: '/apartment',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesAlertsRoute = PreferencesAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesAccountRoute = PreferencesAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PreferencesRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPricingRoute = OnboardingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLoadingRoute = OnboardingLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStepStepRoute = OnboardingStepStepRouteImport.update({
  id: '/step/$step',
  path: '/step/$step',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/preferences': typeof PreferencesRouteWithChildren
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/pricing': typeof OnboardingPricingRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/preferences/account': typeof PreferencesAccountRoute
  '/preferences/alerts': typeof PreferencesAlertsRoute
  '/preferences/apartment': typeof PreferencesApartmentRoute
  '/preferences/budget': typeof PreferencesBudgetRoute
  '/preferences/location': typeof PreferencesLocationRoute
  '/preferences/referrals': typeof PreferencesReferralsRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/onboarding/step/$step': typeof OnboardingStepStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/pricing': typeof OnboardingPricingRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/preferences/account': typeof PreferencesAccountRoute
  '/preferences/alerts': typeof PreferencesAlertsRoute
  '/preferences/apartment': typeof PreferencesApartmentRoute
  '/preferences/budget': typeof PreferencesBudgetRoute
  '/preferences/location': typeof PreferencesLocationRoute
  '/preferences/referrals': typeof PreferencesReferralsRoute
  '/preferences': typeof PreferencesIndexRoute
  '/onboarding/step/$step': typeof OnboardingStepStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/preferences': typeof PreferencesRouteWithChildren
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/pricing': typeof OnboardingPricingRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/preferences/account': typeof PreferencesAccountRoute
  '/preferences/alerts': typeof PreferencesAlertsRoute
  '/preferences/apartment': typeof PreferencesApartmentRoute
  '/preferences/budget': typeof PreferencesBudgetRoute
  '/preferences/location': typeof PreferencesLocationRoute
  '/preferences/referrals': typeof PreferencesReferralsRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/onboarding/step/$step': typeof OnboardingStepStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/preferences'
    | '/onboarding/loading'
    | '/onboarding/preview'
    | '/onboarding/pricing'
    | '/onboarding/success'
    | '/preferences/account'
    | '/preferences/alerts'
    | '/preferences/apartment'
    | '/preferences/budget'
    | '/preferences/location'
    | '/preferences/referrals'
    | '/preferences/'
    | '/onboarding/step/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/onboarding/loading'
    | '/onboarding/preview'
    | '/onboarding/pricing'
    | '/onboarding/success'
    | '/preferences/account'
    | '/preferences/alerts'
    | '/preferences/apartment'
    | '/preferences/budget'
    | '/preferences/location'
    | '/preferences/referrals'
    | '/preferences'
    | '/onboarding/step/$step'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/preferences'
    | '/onboarding/loading'
    | '/onboarding/preview'
    | '/onboarding/pricing'
    | '/onboarding/success'
    | '/preferences/account'
    | '/preferences/alerts'
    | '/preferences/apartment'
    | '/preferences/budget'
    | '/preferences/location'
    | '/preferences/referrals'
    | '/preferences/'
    | '/onboarding/step/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PreferencesRoute: typeof PreferencesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/'
      fullPath: '/preferences/'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/referrals': {
      id: '/preferences/referrals'
      path: '/referrals'
      fullPath: '/preferences/referrals'
      preLoaderRoute: typeof PreferencesReferralsRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/location': {
      id: '/preferences/location'
      path: '/location'
      fullPath: '/preferences/location'
      preLoaderRoute: typeof PreferencesLocationRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/budget': {
      id: '/preferences/budget'
      path: '/budget'
      fullPath: '/preferences/budget'
      preLoaderRoute: typeof PreferencesBudgetRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/apartment': {
      id: '/preferences/apartment'
      path: '/apartment'
      fullPath: '/preferences/apartment'
      preLoaderRoute: typeof PreferencesApartmentRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/alerts': {
      id: '/preferences/alerts'
      path: '/alerts'
      fullPath: '/preferences/alerts'
      preLoaderRoute: typeof PreferencesAlertsRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/account': {
      id: '/preferences/account'
      path: '/account'
      fullPath: '/preferences/account'
      preLoaderRoute: typeof PreferencesAccountRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/pricing': {
      id: '/onboarding/pricing'
      path: '/pricing'
      fullPath: '/onboarding/pricing'
      preLoaderRoute: typeof OnboardingPricingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/preview': {
      id: '/onboarding/preview'
      path: '/preview'
      fullPath: '/onboarding/preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/loading': {
      id: '/onboarding/loading'
      path: '/loading'
      fullPath: '/onboarding/loading'
      preLoaderRoute: typeof OnboardingLoadingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step/$step': {
      id: '/onboarding/step/$step'
      path: '/step/$step'
      fullPath: '/onboarding/step/$step'
      preLoaderRoute: typeof OnboardingStepStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingLoadingRoute: typeof OnboardingLoadingRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  OnboardingPricingRoute: typeof OnboardingPricingRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingStepStepRoute: typeof OnboardingStepStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLoadingRoute: OnboardingLoadingRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  OnboardingPricingRoute: OnboardingPricingRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingStepStepRoute: OnboardingStepStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PreferencesRouteChildren {
  PreferencesAccountRoute: typeof PreferencesAccountRoute
  PreferencesAlertsRoute: typeof PreferencesAlertsRoute
  PreferencesApartmentRoute: typeof PreferencesApartmentRoute
  PreferencesBudgetRoute: typeof PreferencesBudgetRoute
  PreferencesLocationRoute: typeof PreferencesLocationRoute
  PreferencesReferralsRoute: typeof PreferencesReferralsRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
}

const PreferencesRouteChildren: PreferencesRouteChildren = {
  PreferencesAccountRoute: PreferencesAccountRoute,
  PreferencesAlertsRoute: PreferencesAlertsRoute,
  PreferencesApartmentRoute: PreferencesApartmentRoute,
  PreferencesBudgetRoute: PreferencesBudgetRoute,
  PreferencesLocationRoute: PreferencesLocationRoute,
  PreferencesReferralsRoute: PreferencesReferralsRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
}

const PreferencesRouteWithChildren = PreferencesRoute._addFileChildren(
  PreferencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PreferencesRoute: PreferencesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
